export enum Role {
    USER = 'USER',
    ADMIN_RESOURCE = 'ADMIN_RESOURCE',
    ADMIN_RESERVATION = 'ADMIN_RESERVATION',
    SUPERUSER = 'SUPERUSER',
    VIGILANCIA = 'VIGILANCIA',
    CALENDAR_VIEWER = 'CALENDAR_VIEWER',
}
